import type { Ad, Stat, EngagementData } from './types';
import { BarChart, Target, TrendingUp, Users } from 'lucide-react';

export const stats: Stat[] = [
  {
    title: 'Publicités Suivies',
    value: '12,405',
    change: '+12.5%',
    changeType: 'increase',
    icon: BarChart,
  },
  {
    title: 'Produits Gagnants',
    value: '237',
    change: '+3.2%',
    changeType: 'increase',
    icon: Target,
  },
  {
    title: 'Engagement Supérieur',
    value: '89.7%',
    change: '-1.8%',
    changeType: 'decrease',
    icon: TrendingUp,
  },
  {
    title: 'Nouveaux Concurrents',
    value: '15',
    change: '+5 depuis la semaine dernière',
    changeType: 'increase',
    icon: Users,
  },
];

export const ads: Ad[] = [
  {
    id: '1',
    title: 'Cozy Knit Sweater',
    platform: 'Pinterest',
    imageUrl: '/images/ad-sweater.png',
    dataAiHint: 'cozy sweater',
    engagement: { likes: 12000, comments: 450, shares: 1200, score: 92 },
    date: '2023-10-26',
    country: 'USA',
    productLink: '/images/ad-sweater.png',
  },
  {
    id: '2',
    title: 'Smart Home Hub',
    platform: 'Facebook',
    imageUrl: '/images/ad-smarthome.png',
    dataAiHint: 'smart home',
    engagement: { likes: 8500, comments: 1200, shares: 900, score: 90 },
    date: '2023-10-25',
    country: 'UK',
    productLink: '/images/ad-smarthome.png',
  },
  {
    id: '3',
    title: 'Organic Skincare Set',
    platform: 'Instagram',
    imageUrl: '/images/ad-skincare.png',
    dataAiHint: 'skincare set',
    engagement: { likes: 25000, comments: 3500, shares: 2000, score: 88 },
    date: '2023-10-24',
    country: 'Canada',
    productLink: '/images/ad-skincare.png',
  },
  {
    id: '4',
    title: 'Portable Blender',
    platform: 'TikTok',
    imageUrl: '/images/ad-blender.png',
    dataAiHint: 'portable blender',
    engagement: { likes: 500000, comments: 15000, shares: 25000, score: 85 },
    date: '2023-10-23',
    country: 'Australia',
    productLink: '/images/ad-blender.png',
  },
  {
    id: '5',
    title: 'Noise-Cancelling Headphones',
    platform: 'Facebook',
    imageUrl: '/images/ad-headphones.png',
    dataAiHint: 'headphones music',
    engagement: { likes: 7200, comments: 800, shares: 500, score: 82 },
    date: '2023-10-22',
    country: 'Germany',
    productLink: '/images/ad-headphones.png',
  },
  {
    id: '6',
    title: 'Yoga Mat & Block Set',
    platform: 'Pinterest',
    imageUrl: '/images/ad-yoga.png',
    dataAiHint: 'yoga mat',
    engagement: { likes: 18000, comments: 600, shares: 2500, score: 80 },
    date: '2023-10-21',
    country: 'USA',
    productLink: '/images/ad-yoga.png',
  },
  {
    id: '7',
    title: 'Subscription Box',
    platform: 'Instagram',
    imageUrl: '/images/ad-subbox.png',
    dataAiHint: 'subscription box',
    engagement: { likes: 32000, comments: 2800, shares: 1500, score: 79 },
    date: '2023-10-20',
    country: 'UK',
    productLink: '/images/ad-subbox.png',
  },
  {
    id: '8',
    title: 'LED Strip Lights',
    platform: 'TikTok',
    imageUrl: '/images/ad-led.png',
    dataAiHint: 'led lights',
    engagement: { likes: 800000, comments: 25000, shares: 40000, score: 75 },
    date: '2023-10-19',
    country: 'USA',
    productLink: '/images/ad-led.png',
  },
];

export const engagementData: EngagementData[] = [
  { date: 'Lun', Facebook: 2200, Instagram: 3400, TikTok: 4500, Pinterest: 1200 },
  { date: 'Mar', Facebook: 2500, Instagram: 3600, TikTok: 4800, Pinterest: 1500 },
  { date: 'Mer', Facebook: 2800, Instagram: 3800, TikTok: 5200, Pinterest: 1700 },
  { date: 'Jeu', Facebook: 3100, Instagram: 4100, TikTok: 5500, Pinterest: 1900 },
  { date: 'Ven', Facebook: 3400, Instagram: 4400, TikTok: 6000, Pinterest: 2100 },
  { date: 'Sam', Facebook: 3700, Instagram: 4700, TikTok: 6500, Pinterest: 2400 },
  { date: 'Dim', Facebook: 4000, Instagram: 5000, TikTok: 7000, Pinterest: 2600 },
];
